# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xls.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='xls.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\txls.proto\"4\n\tAwardItem\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0b\n\x03num\x18\x02 \x02(\x05\x12\x0e\n\x06\x65xpire\x18\x03 \x01(\x05\"\x83\x01\n\x08TaskItem\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04type\x18\x02 \x02(\x05\x12\x0c\n\x04name\x18\x03 \x02(\t\x12\x12\n\nstart_time\x18\x04 \x02(\r\x12\x10\n\x08\x65nd_time\x18\x05 \x02(\r\x12\r\n\x05\x63onds\x18\x06 \x03(\x05\x12\x1a\n\x06\x61wards\x18\x07 \x03(\x0b\x32\n.AwardItem\"#\n\x08TaskList\x12\x17\n\x04list\x18\x01 \x03(\x0b\x32\t.TaskItem'
)




_AWARDITEM = _descriptor.Descriptor(
  name='AwardItem',
  full_name='AwardItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='AwardItem.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num', full_name='AwardItem.num', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expire', full_name='AwardItem.expire', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=65,
)


_TASKITEM = _descriptor.Descriptor(
  name='TaskItem',
  full_name='TaskItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='TaskItem.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='TaskItem.type', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='TaskItem.name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='TaskItem.start_time', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='TaskItem.end_time', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conds', full_name='TaskItem.conds', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='awards', full_name='TaskItem.awards', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=199,
)


_TASKLIST = _descriptor.Descriptor(
  name='TaskList',
  full_name='TaskList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='TaskList.list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=236,
)

_TASKITEM.fields_by_name['awards'].message_type = _AWARDITEM
_TASKLIST.fields_by_name['list'].message_type = _TASKITEM
DESCRIPTOR.message_types_by_name['AwardItem'] = _AWARDITEM
DESCRIPTOR.message_types_by_name['TaskItem'] = _TASKITEM
DESCRIPTOR.message_types_by_name['TaskList'] = _TASKLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AwardItem = _reflection.GeneratedProtocolMessageType('AwardItem', (_message.Message,), {
  'DESCRIPTOR' : _AWARDITEM,
  '__module__' : 'xls_pb2'
  # @@protoc_insertion_point(class_scope:AwardItem)
  })
_sym_db.RegisterMessage(AwardItem)

TaskItem = _reflection.GeneratedProtocolMessageType('TaskItem', (_message.Message,), {
  'DESCRIPTOR' : _TASKITEM,
  '__module__' : 'xls_pb2'
  # @@protoc_insertion_point(class_scope:TaskItem)
  })
_sym_db.RegisterMessage(TaskItem)

TaskList = _reflection.GeneratedProtocolMessageType('TaskList', (_message.Message,), {
  'DESCRIPTOR' : _TASKLIST,
  '__module__' : 'xls_pb2'
  # @@protoc_insertion_point(class_scope:TaskList)
  })
_sym_db.RegisterMessage(TaskList)


# @@protoc_insertion_point(module_scope)
